Add support for React 18
Shopify/remote-ui pull request #157
Opened 2022-05-27 11:43 UTC by marvinhagemeister

This PR adds support for React 18.

Todos:

- [x] Add compatibility for React 17 back

2022-05-29 09:40 UTC, marvinhagemeister commented on yarn.lock
> +"@types/react@^18.0.9":
Just checked and that package isn't listed as a candidate for deduping. Looks like `@quilted/react-testing` pulls that in by being pulling in React 17.x dependencies.

2022-05-30 13:37 UTC, lemonmade requested changes

2022-11-22 19:12 UTC, skaplan-dev commented
Hey, @lemonmade and @marvinhagemeister. My team at [HubSpot](https://developers.hubspot.com/) is building a new UI Extensions platform, and we are evaluating `remote-ui` as an option. We would love this PR to be merged so our team can integrate it into our stack. Is there anything blocking this, or anything our team can do to help? Cheers! :)

2022-12-09 03:00 UTC, lemonmade commented
This was done as part of https://github.com/Shopify/remote-ui/pull/191, and will be part of the 5.0.0 release of that package. Thanks @marvinhagemeister for getting this started!

2022-12-09 03:00 UTC, closed without merging